### ISSUE TITLE
How do I install LiveView?

### ISSUE THREAD

**Issue by lewismc** [nasa-jpl/LiveViewOpenSource#19]
Hi Folks, how do I install this software? What are the build artifacts and how do I use it? Thanks

**Comment by jackiryan** [comment]
Hi Lewis,
The simplest way you can install LiveView is by cloning the repository and running `qmake` and then `make -j` from within the source directory. In general, you may want certain ancillary software on your system to support different types of cameras. You can find a detailed guide here:
[https://github.com/nasa-jpl/LiveViewOpenSource/wiki/Installation-Guide](https://github.com/nasa-jpl/LiveViewOpenSource/wiki/Installation-Guide)
Although that guide is mainly intended for developers, it may be helpful to you as well.

The build will produce a new directory containing the application itself, along with .o files and some other compilation artifacts. 

The purpose of the software is for imaging spectrometer Integration and Testing (I&T), as well as general purpose imaging GSE software. If you'd like to see how to run the included test data, see this wiki page:
[https://github.com/nasa-jpl/LiveViewOpenSource/wiki/Getting-started-with-the-sample-data](https://github.com/nasa-jpl/LiveViewOpenSource/wiki/Getting-started-with-the-sample-data)

**Comment by lewismc** [comment]
@jackiryan thanks for your response. Some questions as I follow the [installation guide](https://github.com/nasa-jpl/LiveViewOpenSource/wiki/Installation-Guide).

> ...To begin, obtain a copy of the source from the JPL GitHub by cloning the repository, entering this command in a terminal: $ git clone https://github.jpl.nasa.gov/jryan/LiveView-Experimental

is it correct to reference https://github.jpl.nasa.gov/jryan/LiveView-Experimental? Should this not be https://github.com/nasa-jpl/LiveViewOpenSource/?

> ...For git to work properly, ensure that you have logged into JPL GitHub at least once.

This is simply impossible for anyone outside of JPL to do... 

In the [installing-on-unix-based-operating-systems](https://github.com/nasa-jpl/LiveViewOpenSource/wiki/Installation-Guide#installing-on-unix-based-operating-systems) section, I highly suggest providing a hyperlink to **_qtcreator_** . I have no idea what it is and I don't fancy installing arbitrary 3rd party software without knowing at least a bit about what it is.

> ...Launch QtCreator, and open LiveView.pro

How do I launch QtCreator? I downloaded via Homebrew on Mac OS. 
As it turns out, I need to do the following
```
brew cask install qt-creator
```
You can then open LiveView.pro as follows
```
open LiveView.pro
```

After setting the `-f` flag on the `make` build configuration and once I managed to build with the hammer icon, my build output flags the following issues
```
../LiveViewOpenSource/src/main.cpp:33:25: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
    char* socket_path = "/tmp/LiveViewOpenSource";
                        ^
In file included from obj/moc_cameraselectdialog.cpp:9:
obj/../../LiveViewOpenSource/include/cameraselectdialog.h:122:19: warning: private field 'w' is not used [-Wunused-private-field]
    LVMainWindow *w;
                  ^
obj/../../LiveViewOpenSource/include/cameraselectdialog.h:127:16: warning: private field 'formatListView' is not used [-Wunused-private-field]
    QListView *formatListView;
               ^
obj/../../LiveViewOpenSource/include/cameraselectdialog.h:129:23: warning: private field 'formatListModel' is not used [-Wunused-private-field]
    QStringListModel *formatListModel;
                      ^
1 warning generated.
3 warnings generated.
```
It did however build successfully and I was able to run LiveView.

**Comment by lewismc** [comment]
I was not able to open any sample data as per https://github.com/nasa-jpl/LiveViewOpenSource/wiki/Getting-started-with-the-sample-data

I was asked to choose between XIO and ENVI. When I choose either one I was asked to define the X, Y dimensions of the input... which I do not know. I tried arbitrary numbers and was allowed to proceed.
Upon navigating to the example datasets they are not available for selection... I am therefore unable to progress.

**Comment by jackiryan** [comment]
@lewismc Great feedback! That installation guide was actually ported from an old document that we handed out to scientists and I&T folks to help them get the software set up in their labs. I'll update with better information, since I don't think it needs to be mentioned anymore that you need a Github account when reading a document *on Github*. I'll also change the link to point to the correct version of the repository. Originally this codebase was maintained on our Enterprise Github, but we ported it over after the open source paperwork was finished.

QtCreator is the IDE I use to build and develop our software. It is a mature and safe editor made by the Qt Company. I can provide a link to what it is. It also occurs to me that some people might want to install such dependencies under a containerization scheme, but I'm not sure how to account for that since I personally do not use containerized infrastructure.

QtCreator itself can be launched simply by typing the following command at the console:
```
    $ qtcreator &
```
or by clicking its icon in the applications drawer (i.e., on Mac).

I can fix those compiler warnings in a bit, they weren't caught by my static analyzer.

**Comment by jackiryan** [comment]
I can update the "Getting started" section, it makes assumptions that may not be friendly to new users.

The SSD (ENVI) mode is not mature yet because we don't use it in our lab, but some customers have expressed interest. So, you will want to select the SSD (XIO) option, then set a frame geometry of 640 (width) by 480 (height). Then you can select a **directory** containing data, e.g., the ROICWARM (lab data) or FPAEMULATOR (FPGA-generated test pattern). The files in the directory will play until there is no data left. You can replay with Ctrl + R or Cmd + R on Mac.
